---

deployment:
  name: email-service
  image: vpnbeast/email-service:1.1.17
  replicaCount: 1
  ports:
    - containerPort: 8090
      name: server-port
    - containerPort: 8091
      name: management-port
  variables:
    - name: TZ
      value: Europe/Istanbul
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: CONFIG_SERVICE_HOST
      value: config-service
    - name: CONFIG_SERVICE_PORT
      value: 8888
  probes:
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /actuator/health
        port: 8091
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /actuator/health
        port: 8091
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10

service:
  ports:
    - name: server-port
      port: 8090
      targetPort: 8090
    - name: management-port
      port: 8091
      targetPort: 8091